# Site settings
title: The blog of Victor
description: welcome to my blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
 url: "https://victor-zwb.github.io" 

# User settings
username: 易水未暖
user_description: 待养成的程序猿/半吊子诗人&写手/假的文艺青年
user_title: 待养成的程序猿/半吊子诗人&写手/假的文艺青年
email: 2083000569@qq.com
jianshu_username: 46e9e654a9e0
github_username:  Victor Zhang
zhihu_username:  易水未暖

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
